version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: bookdb_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookDB

    volumes:
      - ./mysql_data:/var/lib/mysql