version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: suryansh
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-go
    ports:
      - "5000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data